# Site settings
title: Spring 2017 MEC 262 course page
email: 
description: "Course material for MEC 262: Engineering Dynamics taught at Stony Brook University by Dr. Vivek Yadav"
baseurl: ""
url: "http://mec262sp17.github.io"
github_username:  mec262sp17

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
